services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  todo-backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    ports:
      - "15000:15000"
    depends_on:
      - mongo

  todo-frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost:15000
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend

volumes:
  mongo-data: